# Generated by Django 2.2.11 on 2023-01-22 15:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sourceFile', models.FileField(null=True, upload_to='uploads/')),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('ip_address', models.GenericIPAddressField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='myusername', max_length=100, unique=True)),
                ('serial_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='File', to='piracyApp.File')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='piracyApp.User')),
            ],
        ),
    ]
