# Generated by Django 2.2.11 on 2023-01-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piracyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
