# Generated by Django 2.2.11 on 2023-01-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piracyApp', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='myusername', max_length=100),
        ),
    ]
